language: node_js
sudo: false
node_js:
  - "9"
python:
  - "2.7"
install:
  - npm install
script:
  - npm run build
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      npm run redeploy-site;
    fi
notifications:
  email:
    on_success: never
    on_failure: always
