language: node_js
sudo: false
node_js:
  - "9"
python:
  - "2.7"
install:
  - npm install
script:
  - npm run build
  - npm run lint
notifications:
  email:
    on_success: never
    on_failure: always
