language: node_js
sudo: false
dist: bionic
node_js:
  - "10"
  - "12"
python:
  - "3.8"
install:
  - npm install
script:
  - npm run build
  - npm run lint
notifications:
  email:
    on_success: never
    on_failure: always
